### ISSUE TITLE
segfault under wayland

### ISSUE THREAD

**Issue by titaniumbones** [Aerilius/eog_panorama#13]
Hi, I am trying to view a google/android VR-style panorama under arch linux, GNOME 3.32.1, under Wayland. I get the following error & segfault: 
> gdk_window_create_gl_context: assertion 'GDK_IS_WINDOW (window)' failed

I have no idea whether or nto this is wayland related, but would appreciate any help you can give. Thanks!

**Comment by Aerilius** [comment]
Sorry, I am not a Wayland developer or have any clue about it. 

This plugin just uses the plain python GTK APIs and I expect those to work on any desktop or display server. If not, it is a bug in something in the underlying softwares, not something I can easily influence. 
Maybe someone else has an idea?
