### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by gazhay** [Aerilius/eog_panorama#8]
Installed into ~/.local/share/eog/plugins
Appears in Edit -> Preferences -> Plugins

Trying to enable I get a red stop sign.

![selection_002](https://cloud.githubusercontent.com/assets/871127/22701482/a6eda3a6-ed55-11e6-9940-0dd817e5a30f.png)
![selection_001](https://cloud.githubusercontent.com/assets/871127/22701483/a6eddd94-ed55-11e6-935d-e0a25992fbd3.png)

**Comment by stefanhorning** [comment]
Same here, with EOG version 3.20.4 and only fullscreen plugin activated.

**Comment by stefanhorning** [comment]
Nevermind, a `sudo apt install gir1.2-gexiv2-0.10` fixed it.

However, the plugin doesn't appear to do anything when loading a panoramic picture.

**Comment by gazhay** [comment]
Can confirm stefanhorning's fix works

**Comment by Aerilius** [comment]
Thanks for confirming that the missing dependency was the issue! Assuming there is nothing else I am closing this.
